from build_dim import main_build_dim
from build_fact_gdp import main_build_fact_gdp
from build_fact_crop import main_build_fact_crop
from build_fact_production import main_build_fact_production_output
from buid_fact_total_investment import main_build_fact_total_investment
from build_fact_trade_international_fact import main_build_fact_trade_international


main_build_dim()
main_build_fact_gdp()
main_build_fact_crop()
main_build_fact_production_output()
main_build_fact_trade_international()
main_build_fact_total_investment()

